[NFC][Comgr] Remove DemangleTest dependency with LLVM Support (#2864)
Due to a header in gtest bringing in some llvm symbols, `DemangleTest`
depended on the abi-breaking checks; even though it used none.

Compilation failed with:
```
/usr/bin/ld:
tools/comgr/test-unit/CMakeFiles/DemangleSymbolNameTest.dir/DemangleSymbolNameTest.cpp.o:
undefined reference to symbol '_ZN4llvm23EnableABIBreakingChecksE'
/usr/bin/ld: _build/lib/libLLVMSupport.so.23.0git: error adding symbols: DSO missing from command line
```

This patch breaks the dependency by disabling gtest's LLVM extensions
for this test, since they're unused.

(reopen of https://github.com/ROCm/llvm-project/pull/2851 that I wrongly
merged over the wrong user branch).

Depends on https://github.com/ROCm/llvm-project/pull/2850